### PR TITLE
Use PATCH to change session kernel

### PR DESCRIPTION
**Pull request by blink1073**
Relies on https://github.com/jupyter/notebook/pull/1206.

### CODE REVIEW

**Comment by minrk** [comment]
Merged upstream, if you want to bump things here. It's a little disconcerting that the tests are passing prior to the upstream patch being merged. Is this behavior not tested?

**Comment by blink1073** [comment]
I didn't have a way to test agaist the notebook server itself, only the logic.  I'll add that test.

**Comment by blink1073** [comment]
It would be cleaner to have a `changeKernel(name: string)` and a `connectToKernel(id: string)` instead, what do you think, @minrk?

**Comment by minrk** [comment]
where connectToKernel produces a new session, while changeKernel always gets a new kernel? That leaves out `changeKernel(kernel_id)`, where you have a notebook running and want to attach it to a running kernel.

**Comment by blink1073** [comment]
No, what I *really* want to do is add `kernelId` to `ISessionOptions` and then have one function called `NotebookSession.changeKernel(options: ISessionOptions)`, and use the `kernelId` when starting a new session.  So, maybe I'll make the PR against notebook first to do that.

**Comment by blink1073** [comment]
This part is done.  I'll add the ability to connect to an existing session after https://github.com/jupyter/notebook/pull/1237 is merged.

**Comment by minrk** [comment]
Merged that, but this needs a rebase now. Will merge when it applies.

**Comment by blink1073** [comment]
Ready to roll.

**Comment by minrk** [comment]
rolling :bowling:

**Pull request merged**
