### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
I'll wait for #35, rebase, and clean up the Ajax options docs afterwards (trying to reduce merge conflicts as much as possible).

**Comment by minrk** [comment]
Merged #35

**Comment by blink1073** [comment]
This is ready.

**Comment by minrk** [comment]
Looking really nice, thanks @blink1073!

**Comment by minrk** [comment]
Is there a readthedocs-style service for hosting js docs? We could use Travis + gh-pages, but I really don't like filling a code repo with incremental builds of docs.

**Comment by blink1073** [comment]
We could deploy from Travis directly to a host somewhere (potentially at Rackspace), and not store the incremental builds.

**Pull request merged**
