### PR TITLE
Add GH_REF to the travis.yml

### PR DESCRIPTION
**Pull request by rgbkrk**
Whoops. Should have been part of #6

### CODE REVIEW

**Comment by blink1073** [comment]
Want to make this into a `deploy` target in `package.json` as well?

**Comment by blink1073** [comment]
Unify :allthethings:?

**Comment by rgbkrk** [comment]
Actually, I just realized we should be using a deploy target in travis too.

**Comment by rgbkrk** [comment]
And yes.

**Comment by rgbkrk** [comment]
Apparently the `deploy:` tag in Travis only has some providers. We'll keep running this in `after_success`.

**Comment by blink1073** [comment]
I'll take it, thanks.

**Comment by blink1073** [comment]
Well, damn: https://travis-ci.org/jupyter/jupyter-js-services#L305

**Pull request merged**
