### PR TITLE
Chain promises when handling comm_open

### PR DESCRIPTION
**Pull request by jhpedemonte**
Fixes ipython/ipywidgets#561

### CODE REVIEW

**Comment by jhpedemonte** [comment]
Other part of fix: https://github.com/ipython/ipywidgets/pull/594

**Comment by SylvainCorlay** [comment]
Thanks for fixing this @jhpedemonte .

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
Released as `v0.10.2`.

**Pull request merged**
