### PR TITLE
Finish kernel tests

### PR DESCRIPTION
**Pull request by blink1073**
Round out the kernel tests.

Before:

screen shot 2015-08-21 at 12 05 19 pm

After:

screen shot 2015-08-21 at 12 04 27 pm

### CODE REVIEW

**Comment by blink1073** [comment]
This is ready.

**Comment by blink1073** [comment]
Hold on, I forgot to include binary messages.

**Comment by rgbkrk** [comment]
Okee doke, good thing you changed that title while I was reading. :wink:

**Comment by blink1073** [comment]
Ok, now it is ready.  Note that there is no coverage of `session` yet, which should also round out the `utils` tests.

screen shot 2015-08-21 at 2 28 02 pm

**Comment by blink1073** [comment]
@minrk, do you mind enabling this repo on coveralls?

**Pull request merged**
