### PR TITLE
[WIP] KernelSpec

### PR DESCRIPTION
**Pull request by blink1073**
screen shot 2015-08-24 at 4 02 02 pm

Usage [example](https://github.com/blink1073/jupyter-js-services/blob/kernelspec/README.md#usage-examples).

### CODE REVIEW

**Comment by blink1073** [comment]
@rgbkrk, I did this one first because it was easier :smile:

**Comment by rgbkrk** [comment]
Haha that's totally cool.

**Comment by blink1073** [comment]
@rgbkrk, hold off on these PRs, I'm going to unify the API for Services objects in another PR.  I'm going to add an `onReady` Promise to each of the objects, that is fulfilled at the appropriate time.  For example, for the `Kernel`, it would fulfill the first time we get a `kernel_info_reply` over the WebSocket.

**Comment by blink1073** [comment]
Merged into #20, because we need the `Kernelspec` for integration testing.

**Pull request closed without merging**
