### PR TITLE
Add a published webpack bundle

### LINKED ISSUE #160: Make a single .js file that can be included in other projects
We would like to use the jupyter-js-services library, however it would be very complicated to include an ```npm build``` style workflow into our project. 

It would be great if there was a single ```jupyter-js-services.js``` that file that we could just include into our html page without having to include additional libraries. Something like [webpack](https://webpack.github.io/) or [browserify](http://browserify.org/) can do this. If we do this on our end, it means a significant effort every time we want to update to the newest version, so we were hoping that you could generate single such a file somewhere in this repository. 

/cc @florian-rabe @minrk

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #160.

cc @tkw1536 @SylvainCorlay

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
LGTM!

**Comment by SylvainCorlay** [comment]
@tkw1536, once a version is published with this patch, you should be able to amd-require (requirejs) 

`https://npmcdn.com/jupyter-js-services/dist/index.js`

or even add a semver requirement, e.g.

`https://npmcdn.com/jupyter-js-services@^0.12.0/dist/index.js`

**Comment by blink1073** [comment]
Published as `jupyter-js-services@0.11.4`.

**Comment by SylvainCorlay** [comment]
OK, fixed the URL above.

**Comment by SylvainCorlay** [comment]
Hum, actually, I think that npmcdn prefers the main js file to be `index.js`

**Comment by SylvainCorlay** [comment]
so that you can only require
`https://npmcdn.com/jupyter-js-services@0.11.4/dist/`

**Comment by SylvainCorlay** [comment]
I don't really know if it is important. We could probably decide for a pattern at some point.

It would be really cool that one could make a pure cdn-hosted client to jupyter with npmcdn.

**Comment by blink1073** [comment]
Yeah, whatever we do it should be consistent.

**Comment by minrk** [comment]
Awesome, thanks @blink1073! We should probably do the same for jupyterlab at some point.

**Comment by blink1073** [comment]
Yep, that is the next target ;).

**Pull request merged**
