### PR TITLE
Add shutdown reply iopub message

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by minrk** [comment]
From https://github.com/jupyter/jupyter_client/pull/113, I think this shouldn't be added. The client should log this as an unhandled message and move on. Is this not what happens?

**Comment by blink1073** [comment]
Right now it is an error, I'll open a PR to make it just log.

**Comment by blink1073** [comment]
Actually, not needed, I was only seeing a problem because I had "Pause on caught exceptions", the current behavior is correct.

**Comment by minrk** [comment]
Great, that's what the code looked like to me.

**Pull request closed without merging**
