### PR TITLE
API Upgrades

### LINKED ISSUE #57: ajaxRequest should warn on invalid/undefined `settings.methods`
And generally I would have expected the API to be closer to $.ajax the setting/option distinction is bit annoying to refactor when we already have layers of call in JS. 

Here I was caught by GET not being the default.

### LINKED ISSUE #60: Add a cache option
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Bypassing_the_cache

### PR DESCRIPTION
**Pull request by blink1073**
- Improves the API of `ajaxRequest` (Fixes #57).
- Disables cache on the same methods as the current notebook (Fixes #60).
- Moves `ajaxSettings` to the object level and makes them optional, to account for implementations that may not use ajax, or consumers of the object that would not have access to the proper settings otherwise.
- Cleans up the API for functions in `kernel.ts` and `session.ts`, which now take `IKernelOptions` and `ISesssionOptions` across the board.
- Renames `IContent` to `IContentsManager` for clarity.
- Adds `IKernelManager` and `INotebookSessionManager` and associated implementations that abstract the `baseUrl` and `ajaxSettings` for a consumer.

cc @parente @Carreau @minrk

### CODE REVIEW

**Comment by blink1073** [comment]
This is ready for review.  I will be dog-fooding it tomorrow in a `jupyter-js-filebrowser` branch.

**Comment by blink1073** [comment]
I set this back to WIP because the new `*Manager` classes need tests.

**Comment by blink1073** [comment]
Finished and dog-fooded in https://github.com/jupyter/jupyter-js-filebrowser/pull/25.

**Comment by blink1073** [comment]
I've been using this without issue for the past three weeks, any objections to merging?

**Comment by parente** [comment]
Doesn't look like anything will impact us over in dashboards. LGTM.

**Comment by jasongrout** [comment]
I just realized the npm version already had this merged.

**Comment by blink1073** [comment]
Yes, I needed it to continue work on the filebrowser.

**Comment by jasongrout** [comment]
Thanks!  Given @parente's +1, and I glanced at it too, let's merge.

**Pull request merged**
