### PR TITLE
[WIP] Add Contents API and Config

### PR DESCRIPTION
**Pull request by blink1073**
screen shot 2015-08-24 at 2 27 12 pm

Usage [examples](https://github.com/blink1073/jupyter-js-services/blob/contents/README.md#usage-examples).

### CODE REVIEW

**Comment by blink1073** [comment]
Ready.

**Comment by rgbkrk** [comment]
As you add these, can you make simple examples to put in the README too?

**Comment by blink1073** [comment]
Yep, entering documentation mode...

**Comment by blink1073** [comment]
Finished the examples in the Readme.

**Pull request merged**
